# Generated by `terraform apply` in terraform/ - do not edit by hand, it will be
# overwritten on the next apply. See terraform/outputs.tf for the source values.

ENV_ID=${environment_id}
KAFKA_CLUSTER_ID=${kafka_cluster_id}
SCHEMA_REGISTRY_CLUSTER_ID=${schema_registry_cluster_id}
CLOUD_PROVIDER=${cloud_provider}
CLOUD_REGION=${cloud_region}

BOOTSTRAP_SERVERS=${bootstrap_servers}
KAFKA_API_KEY=${kafka_api_key}
KAFKA_API_SECRET=${kafka_api_secret}

SCHEMA_REGISTRY_URL=${schema_registry_url}
SCHEMA_REGISTRY_API_KEY=${schema_registry_api_key}
SCHEMA_REGISTRY_API_SECRET=${schema_registry_api_secret}

TOPIC_ITEM_ADDED_TO_STOCK=${topic_item_added_to_stock}
TOPIC_ITEM_PURCHASED=${topic_item_purchased}
TOPIC_CURRENT_INVENTORY=${topic_current_inventory}

STOREFRONT_PRINCIPAL_ID=${storefront_principal_id}

LIGHTNING_API_KEY=${lightning_api_key}
LIGHTNING_API_SECRET=${lightning_api_secret}
